Shop Class Reference
#include <shop.h>
Public Member Functions
void addItem (IItem *item, int price)
void removeItem (int idx)
Remove an item from the shop.
void listItems (Player &player)
bool buyItem (Player &player, int idx)
Buy an item from the shop.
Public Attributes
vector< ShopItem > items
Detailed Description
Definition at line 15 of file shop.h.
Member Function Documentation
addItem()
void Shop::addItem (IItem * item, int price)
Definition at line 7 of file shop.cpp.
                                         {
    items.push_back(ShopItem(item, price));
}
References items.
Referenced by ShopMenu::render().
buyItem()
bool Shop::buyItem (Player & player, int idx)
Buy an item from the shop.
Parameters
player The player buying the item
idx 1-indexed item number
Definition at line 30 of file shop.cpp.
                                          {
    idx -= 1;
    if (idx < 0 || idx >= items.size()) {
        cout << "Invalid item index." << endl;
        return false;
    }
    ShopItem &shopItem = items[idx];
    
    if (player.money < shopItem.price) {
        cout << colorizeText("You don't have enough money!", RED) << endl;
        return false;
    }
    player.addMoney(-shopItem.price);
    cout << "You bought a " << shopItem.item->name << "!" << endl;
    player.inventory.addItem(shopItem.item, false);
    return true;
}
References Inventory::addItem(), Player::addMoney(), colorizeText(), Player::inventory, ShopItem::item, items, Player::money, IItem::name, ShopItem::price, and RED.
Referenced by ShopMenu::render().
listItems()
void Shop::listItems (Player & player)
Definition at line 19 of file shop.cpp.
                                   {
    int idx = 1;
    cout << "Money: " << player.money << endl;
    cout << "[0] Leave" << endl;
    for (ShopItem &shopItem : items) {
        Color textColor = (player.money < shopItem.price) ? RED : GREEN;
        cout << colorizeText("[" + to_string(idx) + "] " + shopItem.item->name + " [Cost: " + to_string(shopItem.price) + "]", textColor) << endl;
        idx += 1;
      }
}
References colorizeText(), GREEN, items, Player::money, and RED.
Referenced by ShopMenu::render().
removeItem()
void Shop::removeItem (int idx)
Remove an item from the shop.
Parameters
idx 1-indexed item number
Definition at line 11 of file shop.cpp.
                             {
    idx -= 1;
    if (idx < 0 || idx >= items.size()) {
        cout << "Invalid item index." << endl;
        return;
    }
    items.erase(items.begin() + idx);
}
References items.
Member Data Documentation
items
vector<ShopItem> Shop::items
Definition at line 17 of file shop.h.
Referenced by addItem(), buyItem(), listItems(), and removeItem().
The documentation for this class was generated from the following files:
src/shop.h
src/shop.cpp