Inventory Class Reference
Inventory class that holds all items for the player.
#include <inventory.h>
Public Member Functions
IItem * addItem (IItem *item, bool animate=true)
Adds an item to inventory.
void listItems ()
Lists all items in the inventory.
bool useItem (int idx, Player &player, Entity *enemy)
Use an item.
void dropItem (int idx)
drop an item.
Private Attributes
vector< IItem * > items
Detailed Description
Inventory class that holds all items for the player.
Definition at line 14 of file inventory.h.
Member Function Documentation
addItem()
IItem * Inventory::addItem (IItem * item, bool animate = true)
Adds an item to inventory.
Parameters
item The item to add
animate Whether to animate the text or not
Returns
Either the item if it was already in the inventory, or nullptr if it was added successfully
Definition at line 7 of file inventory.cpp.
{
    for (IItem *existingItem : items)
    {
        if (existingItem->matches(item))
        {
            if (!existingItem->isInfinite())
            {
                existingItem->increment(item->getCount());
            } else { // Infinite item alr exists
                return existingItem;
            }
            string msg = "You now have " + to_string(existingItem->getCount()) + "x " + existingItem->getName() + "!";
            string border = "\n" + string(msg.length(), '=') + "\n";
            printAnimate(border, 1, animate);
            printAnimate(msg, 10, animate);
            printAnimate(border, 1, animate);
            return nullptr;
        }
    }
    string msg = item->getName() + " added to inventory!";
    string border = "\n" + string(msg.length(), '=') + "\n";
    printAnimate(border, 1, animate);
    printAnimate(msg, 10, animate);
    printAnimate(border, 1, animate);
    items.push_back(item);
    return nullptr;
}
References IItem::getCount(), IItem::getName(), items, and printAnimate().
Referenced by Shop::buyItem().
dropItem()
void Inventory::dropItem (int idx)
drop an item.
not implemented yet.
Parameters
idx 1-indexed item number
Definition at line 98 of file inventory.cpp.
{
}
listItems()
void Inventory::listItems ()
Lists all items in the inventory.
Should probably include the user input functionality too.
Definition at line 37 of file inventory.cpp.
{
    int idx = 1;
    cout << padTo("[Name]", 20) << "|" << padTo("[Type]", 20) << "|" << padTo("[Description]", 50) << "|" << padTo("[Count]", 20) << endl;
    for (IItem *item : items)
    {
        string count = item->isInfinite() ? "Infinite" : to_string(item->getCount()) + "x";
        string numberedName = string("[") + to_string(idx) + "] " + item->getName();
        cout << padTo(numberedName, 20) << "|" << padTo(item->getType(), 20) << "|" << padTo(item->getDesc(), 50) << "|" << padTo(count, 20) << endl;
        idx++;
    }
    cout << "Type the # of the item to use, 0 to exit > ";
}
References items, and padTo().
useItem()
bool Inventory::useItem (int idx, Player & player, Entity * enemy)
Use an item.
Returns true if the item was used successfully, false if it was not
Parameters
idx 1-indexed item number
player The player using the item
enemy The enemy the item is being used on. If the item is not an enemy item, this can be nullptr.
Definition at line 53 of file inventory.cpp.
{
    IItem *item;
    try
    {
        item = items.at(idx - 1);
    }
    catch (...)
    {
        cout << "Invalid item number!" << endl;
        return false;
    }
    bool useResult;
    if (IPlayerItem *playerItem = dynamic_cast<IPlayerItem *>(item))
    {
        useResult = playerItem->use(player);
    }
    else if (IEnemyItem *enemyItem = dynamic_cast<IEnemyItem *>(item))
    {
        if (enemy == nullptr)
        {
            cout << "You can't use that item here!" << endl;
            return false;
        }
        useResult = enemyItem->use(player, *enemy);
    }
    if (!useResult)
    {
        return false;
    }
    if (!item->isInfinite())
    {
        item->decrement(1);
        if (item->isDepleted())
        {
            items.erase(items.begin() + idx - 1);
            delete item;
        }
    }
    return true;
}
References IItem::decrement(), IItem::isDepleted(), IItem::isInfinite(), and items.
Member Data Documentation
items
vector<IItem *> Inventory::items [private]
Definition at line 17 of file inventory.h.
Referenced by addItem(), listItems(), and useItem().
The documentation for this class was generated from the following files:
src/inventory.h
src/inventory.cpp