MainMenu Class Reference
The main menu after all the cutscenes and stuff.
#include <ui.h>
Public Member Functions
MainMenu (Player player)
UserInterface * render () override
Public Member Functions inherited from UIWithPlayer
UIWithPlayer ()
UIWithPlayer (Player player)
Public Member Functions inherited from UserInterface
virtual ~UserInterface ()
Additional Inherited Members
Public Attributes inherited from UserInterface
bool quitGame = false
Protected Attributes inherited from UIWithPlayer
Player player
Detailed Description
The main menu after all the cutscenes and stuff.
Definition at line 42 of file ui.h.
Constructor & Destructor Documentation
MainMenu()
MainMenu::MainMenu (Player player)
Definition at line 78 of file ui.cpp.
: UIWithPlayer(player) {}
References UIWithPlayer::player, and UIWithPlayer::UIWithPlayer().
Referenced by render().
Member Function Documentation
render()
UserInterface * MainMenu::render () [override], [virtual]
Implements UserInterface.
Definition at line 80 of file ui.cpp.
{
    cout << "[Main Menu]" << endl;
    cout << "HP: " << player.getHealth() << "/" << player.getMaxHealth() << " ATK: " << player.getAtk() << " DEF: " << player.getDef() << endl;
    cout << "Money: " << player.getMoney() << endl;
    cout << "[1] Inventory" << endl;
    cout << "[2] Grind" << endl;
    cout << "[3] Shop" << endl;
    cout << "[4] Gamble" << endl;
    cout << "[5] Hospital" << endl;
    cout << "[6] Quit" << endl;
    int userInput = inputNum();
    if (userInput == 1)
    {
        player.inventory.listItems();
        int bagInput;
        while (true)
        {
            bagInput = inputNum();
            if (bagInput == 0)
            {
                break;
            }
            else
            {
                if (player.inventory.useItem(bagInput, player, nullptr))
                {
                    break;
                }
            }
        }
        return this;
    }
    else if (userInput == 2)
    {
        Entity enemy = Entity(500, "Random Guy", 70, 50);
        auto win = [=](Player player) -> UserInterface *
        {
            return new MainMenu(player);
        };
        auto lose = [=](Player player) -> UserInterface *
        {
            printAnimate("You lost? In a random battle? How embarrassing.\n");
            return new GameOver();
        };
        return new Battle(player, enemy, 50, win, lose);
    }
    else if (userInput == 3)
    {
        return new ShopMenu(player);
    }
    else if (userInput == 4)
    {
        return new GambleMenu(player);
    }
    else if (userInput == 5)
    {
        printAnimate("You were healed to full health!\n");
        player.fullyHeal();
        return this;
    }
    else if (userInput == 6)
    {
        return new StartMenu();
    }
    else if (userInput == 7)
    {
        player.setMoney(999999);
        return this;
    }
    else
    {
        cout << "That's not one of the options!" << endl;
        return this;
    }
}
References inputNum(), MainMenu(), UIWithPlayer::player, and printAnimate().
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp