IPotion Class Reference
Potions set the type to "Potion".
#include <items.h>
Public Member Functions
IPotion (string n, string d, int c, int strength)
int getStrength ()
Public Member Functions inherited from IPlayerItem
IPlayerItem (string n, string t, string d, int c)
virtual bool use (Player &player)=0
Public Member Functions inherited from IItem
IItem (string n, string t, string d, int c)
virtual ~IItem ()
virtual string getDesc ()
string getName ()
string getType ()
void increment (int amount)
void decrement (int amount)
int getCount ()
bool isInfinite ()
bool isDepleted ()
bool matches (IItem *item)
Public Attributes
int strength
Detailed Description
Potions set the type to "Potion".
Definition at line 48 of file items.h.
Constructor & Destructor Documentation
IPotion()
IPotion::IPotion (string n, string d, int c, int strength)
Definition at line 51 of file items.cpp.
: IPlayerItem(n, "Potion", d, c), strength(strength) {}
References IPlayerItem::IPlayerItem(), and strength.
Referenced by HealthPotion::HealthPotion(), and StrengthPotion::StrengthPotion().
Member Function Documentation
getStrength()
int IPotion::getStrength ()
Definition at line 53 of file items.cpp.
                         {
    return strength;
}
References strength.
Member Data Documentation
strength
int IPotion::strength
Definition at line 51 of file items.h.
Referenced by HealthPotion::getDesc(), StrengthPotion::getDesc(), getStrength(), IPotion(), HealthPotion::use(), and StrengthPotion::use().
The documentation for this class was generated from the following files:
src/items.h
src/items.cpp