HealthPotion Class Reference
Health potions heal the player of course.
#include <items.h>
Public Member Functions
HealthPotion (int c)
bool use (Player &player) override
string getDesc () override
Public Member Functions inherited from IPotion
IPotion (string n, string d, int c, int strength)
int getStrength ()
Public Member Functions inherited from IPlayerItem
IPlayerItem (string n, string t, string d, int c)
Public Member Functions inherited from IItem
IItem (string n, string t, string d, int c)
virtual ~IItem ()
string getName ()
string getType ()
void increment (int amount)
void decrement (int amount)
int getCount ()
bool isInfinite ()
bool isDepleted ()
bool matches (IItem *item)
Additional Inherited Members
Public Attributes inherited from IPotion
int strength
Detailed Description
Health potions heal the player of course.
Definition at line 57 of file items.h.
Constructor & Destructor Documentation
HealthPotion()
HealthPotion::HealthPotion (int c)
Definition at line 57 of file items.cpp.
                                :
IPotion("Health Potion", "", c, 100) {}
References IPotion::IPotion().
Member Function Documentation
getDesc()
string HealthPotion::getDesc () [override], [virtual]
Reimplemented from IItem.
Definition at line 59 of file items.cpp.
{
    return "Heals the user " + to_string(strength) + "HP";
}
References IPotion::strength.
use()
bool HealthPotion::use (Player & player) [override], [virtual]
Implements IPlayerItem.
Definition at line 64 of file items.cpp.
{
    if (player.isFullHealth())
    {
        cout << "You're already at full health!" << endl;
        return false;
    }
    player.heal(strength);
    return true;
}
References Entity::heal(), Entity::isFullHealth(), and IPotion::strength.
The documentation for this class was generated from the following files:
src/items.h
src/items.cpp