Player Class Reference
The Player class is an Entity that has an inventory and money.
#include <entities.h>
Public Member Functions
Player ()
Player (int health, string name, int atk, int def, int money)
void addMoney (int amount)
int getMoney ()
void setMoney (int amount)
bool canAfford (int amount)
bool canAfford (ShopItem &item)
Public Member Functions inherited from Entity
Entity (int health, string name, int atk, int def)
virtual ~Entity ()
void attack (Entity &target, int extraDmg=0)
int getHealth ()
int getMaxHealth ()
bool isFullHealth ()
void fullyHeal ()
bool isAlive ()
void heal (int amount)
void kill ()
bool isDead ()
string getName ()
int getAtk ()
int getDef ()
void boostAtk (int amount)
void boostDef (int amount)
Public Attributes
Inventory inventory
Private Attributes
int money
Additional Inherited Members
Protected Attributes inherited from Entity
Health health
string name
Stats stats
Detailed Description
The Player class is an Entity that has an inventory and money.
Definition at line 52 of file entities.h.
Constructor & Destructor Documentation
Player() [1/2]
Player::Player ()
Definition at line 9 of file entities.cpp.
: Entity(0, "", 0, 0), money(0) {}
References Entity::Entity(), and money.
Player() [2/2]
Player::Player (int health, string name, int atk, int def, int money)
Definition at line 10 of file entities.cpp.
                                                                   : Entity(health, name, atk, def), money(money)
{
    inventory = Inventory();
}
References Entity::Entity(), Entity::health, inventory, money, and Entity::name.
Member Function Documentation
addMoney()
void Player::addMoney (int amount)
Definition at line 15 of file entities.cpp.
{
    if (amount < 0)
    {
        cout << colorizeText("You lost " + to_string(-amount) + " money!", RED) << endl;
    }
    else if (amount == 0)
    {
        cout << "You didn't gain or lose any money." << endl;
    }
    else if (amount > 0)
    {
        cout << colorizeText("You gained " + to_string(amount) + " money!", YELLOW) << endl;
    }
    money += amount;
}
References colorizeText(), money, RED, and YELLOW.
Referenced by Shop::buyItem().
canAfford() [1/2]
bool Player::canAfford (int amount)
Definition at line 42 of file entities.cpp.
{
    return money >= amount;
}
References money.
Referenced by Shop::buyItem(), canAfford(), and Shop::listItems().
canAfford() [2/2]
bool Player::canAfford (ShopItem & item)
Definition at line 47 of file entities.cpp.
                                    {
    return canAfford(item.price);
}
References canAfford(), and ShopItem::price.
getMoney()
int Player::getMoney ()
Definition at line 32 of file entities.cpp.
{
    return money;
}
References money.
Referenced by Shop::listItems().
setMoney()
void Player::setMoney (int amount)
Definition at line 37 of file entities.cpp.
{
    money = amount;
}
References money.
Member Data Documentation
inventory
Inventory Player::inventory
Definition at line 57 of file entities.h.
Referenced by Shop::buyItem(), and Player().
money
int Player::money [private]
Definition at line 55 of file entities.h.
Referenced by addMoney(), canAfford(), getMoney(), Player(), Player(), and setMoney().
The documentation for this class was generated from the following files:
src/entities.h
src/entities.cpp