JovialAftermath Class Reference
The cutscene after the player wins the Jovial fight.
#include <ui.h>
Public Member Functions
JovialAftermath (Player player, string bs)
UserInterface * render () override
Public Member Functions inherited from UIWithPlayer
UIWithPlayer ()
UIWithPlayer (Player player)
Public Member Functions inherited from UserInterface
virtual ~UserInterface ()
Public Attributes
string battleStatus
Public Attributes inherited from UIWithPlayer
Player player
Public Attributes inherited from UserInterface
bool quitGame = false
Detailed Description
The cutscene after the player wins the Jovial fight.
Definition at line 80 of file ui.h.
Constructor & Destructor Documentation
JovialAftermath()
JovialAftermath::JovialAftermath (Player player, string bs)
Definition at line 173 of file ui.cpp.
: UIWithPlayer(player), battleStatus(bs) {}
References battleStatus, UIWithPlayer::player, and UIWithPlayer::UIWithPlayer().
Member Function Documentation
render()
UserInterface * JovialAftermath::render () [override], [virtual]
Implements UserInterface.
Definition at line 174 of file ui.cpp.
{
    if (battleStatus == "win")
    {
        printAnimate(colorizeText("Jovial: I- I lost? I can't believe it...\n", YELLOW) +
                     player.name + ": Yeah, tough luck man. Now get outta here.\n" +
                     colorizeText("Jovial: Okay, geez.\n", YELLOW) +
                     "Villager 2: You saved us! Take these health potions and cash as a form of gratitude from us.\n");
        HealthPotion *hp = new HealthPotion(20);
        player.inventory.addItem(hp);
        player.addMoney(100);
        return new MainMenu(player);
    }
    else if (battleStatus == "lose")
    {
        printAnimate("Jovial: Finally. This will make up for the race I lost!\n");
        return new GameOver();
    }
    else
    {
        cout << "Error: Invalid battle status." << endl;
    }
    return this;
}
References battleStatus, colorizeText(), UIWithPlayer::player, printAnimate(), and YELLOW.
Member Data Documentation
battleStatus
string JovialAftermath::battleStatus
Definition at line 83 of file ui.h.
Referenced by JovialAftermath(), and render().
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp