Entity Class Reference
Base class for all entities in the game. This includes the player and enemies.
#include <entities.h>
Public Member Functions
Entity (int health, string name, int atk, int def)
virtual ~Entity ()
void attack (Entity &target, int extraDmg=0)
int getHealth ()
int getMaxHealth ()
bool isFullHealth ()
void fullyHeal ()
bool isAlive ()
void heal (int amount)
void kill ()
bool isDead ()
string getName ()
int getAtk ()
int getDef ()
void boostAtk (int amount)
void boostDef (int amount)
Protected Attributes
Health health
string name
Stats stats
Detailed Description
Base class for all entities in the game. This includes the player and enemies.
Definition at line 25 of file entities.h.
Constructor & Destructor Documentation
Entity()
Entity::Entity (int health, string name, int atk, int def)
Definition at line 55 of file entities.cpp.
                                                       :
health(health, health), stats(Stats(atk, def)), name(name) {}
References health, name, and stats.
Referenced by attack(), Player::Player(), Player::Player(), and ~Entity().
~Entity()
Entity::~Entity () [virtual], [default]
References Entity().
Member Function Documentation
attack()
void Entity::attack (Entity & target, int extraDmg = 0)
Definition at line 58 of file entities.cpp.
{
    int calcDmg = max(1, (stats.atk + extraDmg) - target.stats.def);
    target.health.current = max(0, target.health.current - calcDmg);
    cout << target.getName() << " took " << calcDmg << " DMG!" << endl;
}
References Health::current, Stats::def, Entity(), getName(), health, and stats.
Referenced by Weapon::use().
boostAtk()
void Entity::boostAtk (int amount)
Definition at line 106 of file entities.cpp.
                                {
    stats.atk += amount;
}
References stats.
Referenced by StrengthPotion::use().
boostDef()
void Entity::boostDef (int amount)
Definition at line 110 of file entities.cpp.
                                {
    stats.def += amount;
}
References stats.
fullyHeal()
void Entity::fullyHeal ()
Definition at line 74 of file entities.cpp.
                      {
    health.current = health.max;
    printAnimate(name + " was fully healed!\n");
}
References health, name, and printAnimate().
getAtk()
int Entity::getAtk ()
Definition at line 98 of file entities.cpp.
                   {
    return stats.atk;
}
References stats.
Referenced by StrengthPotion::use().
getDef()
int Entity::getDef ()
Definition at line 102 of file entities.cpp.
                   {
    return stats.def;
}
References stats.
getHealth()
int Entity::getHealth ()
Definition at line 65 of file entities.cpp.
                      {
    return health.current;
}
References health.
getMaxHealth()
int Entity::getMaxHealth ()
Definition at line 68 of file entities.cpp.
                        {
    return health.max;
}
References health.
getName()
string Entity::getName ()
Definition at line 94 of file entities.cpp.
                       {
    return name;
}
References name.
Referenced by attack().
heal()
void Entity::heal (int amount)
Definition at line 82 of file entities.cpp.
                           {
    health.current = min(health.max, health.current + amount);
}
References health.
Referenced by HealthPotion::use().
isAlive()
bool Entity::isAlive ()
Definition at line 79 of file entities.cpp.
                    {
    return health.current > 0;
}
References health.
isDead()
bool Entity::isDead ()
Definition at line 90 of file entities.cpp.
                    {
    return health.current == 0;
}
References health.
isFullHealth()
bool Entity::isFullHealth ()
Definition at line 71 of file entities.cpp.
                         {
    return health.current == health.max;
}
References health.
Referenced by HealthPotion::use().
kill()
void Entity::kill ()
Definition at line 86 of file entities.cpp.
                 {
    health.current = 0;
}
References health.
Member Data Documentation
health
Health Entity::health [protected]
Definition at line 28 of file entities.h.
Referenced by attack(), Entity(), fullyHeal(), getHealth(), getMaxHealth(), heal(), isAlive(), isDead(), isFullHealth(), kill(), and Player::Player().
name
string Entity::name [protected]
Definition at line 29 of file entities.h.
Referenced by Entity(), fullyHeal(), getName(), and Player::Player().
stats
Stats Entity::stats [protected]
Definition at line 30 of file entities.h.
Referenced by attack(), boostAtk(), boostDef(), Entity(), getAtk(), and getDef().
The documentation for this class was generated from the following files:
src/entities.h
src/entities.cpp