Weapon Class Reference
Weapons set the type to "Weapon" and implement the use function cuz all weapons attack lmao.
#include <items.h>
Public Member Functions
Weapon (string name, string desc, int count, int dmg)
bool use (Player &player, Entity &enemy) override
int getDmg ()
Public Member Functions inherited from IEnemyItem
IEnemyItem (string n, string t, string d, int c)
Public Member Functions inherited from IItem
IItem (string n, string t, string d, int c)
virtual ~IItem ()
virtual string getDesc ()
string getName ()
string getType ()
void increment (int amount)
void decrement (int amount)
int getCount ()
bool isInfinite ()
bool isDepleted ()
bool matches (IItem *item)
Public Attributes
int dmg
Detailed Description
Weapons set the type to "Weapon" and implement the use function cuz all weapons attack lmao.
Derived classes only need to set the name, desc, and dmg in the constructor
Definition at line 77 of file items.h.
Constructor & Destructor Documentation
Weapon()
Weapon::Weapon (string name, string desc, int count, int dmg)
Definition at line 91 of file items.cpp.
: IEnemyItem(name, "Weapon", desc, count), dmg(dmg) {}
References IItem::count, IItem::desc, dmg, IEnemyItem::IEnemyItem(), and IItem::name.
Referenced by CoolStick::CoolStick(), and Yamato::Yamato().
Member Function Documentation
getDmg()
int Weapon::getDmg ()
Definition at line 93 of file items.cpp.
{
    return dmg;
}
References dmg.
use()
bool Weapon::use (Player & player, Entity & enemy) [override], [virtual]
Implements IEnemyItem.
Definition at line 98 of file items.cpp.
{
    player.attack(enemy, dmg);
    return true;
}
References Entity::attack(), and dmg.
Member Data Documentation
dmg
int Weapon::dmg
Definition at line 80 of file items.h.
Referenced by CoolStick::getDesc(), Yamato::getDesc(), getDmg(), GambleMenu::render(), use(), and Weapon().
The documentation for this class was generated from the following files:
src/items.h
src/items.cpp