JovialCutscene Class Reference
The cutscene before the player fights Jovial.
#include <ui.h>
Public Member Functions
JovialCutscene (Player player)
UserInterface * render () override
Public Member Functions inherited from UIWithPlayer
UIWithPlayer ()
UIWithPlayer (Player player)
Public Member Functions inherited from UserInterface
virtual ~UserInterface ()
Additional Inherited Members
Public Attributes inherited from UserInterface
bool quitGame = false
Protected Attributes inherited from UIWithPlayer
Player player
Detailed Description
The cutscene before the player fights Jovial.
Definition at line 92 of file ui.h.
Constructor & Destructor Documentation
JovialCutscene()
JovialCutscene::JovialCutscene (Player player)
Definition at line 289 of file ui.cpp.
: UIWithPlayer(player) {}
References UIWithPlayer::player, and UIWithPlayer::UIWithPlayer().
Member Function Documentation
render()
UserInterface * JovialCutscene::render () [override], [virtual]
Implements UserInterface.
Definition at line 290 of file ui.cpp.
{
    printAnimate(string("Villager 1: Hey, did you know? Jovial lost the final race today...\n") +
                 "Villager 2: What?? That can't be! She's the best horse there is. I put all my money on her and she LOST???\n" +
                 "Villager 1: Okay, calm your horses (hehe). It's gonna be fine.\n" +
                 "Villager 2: NO IT WON'T!! When I see that horse again, I'll... I'll...\n" +
                 colorizeText("Jovial: You'll what?\n", YELLOW) +
                 "*Jovial approaches Villager 2 very menacingly*\n\n" +
                 player.getName() + ": STOP!! If anybody's fighting, it'll be you and me, Jovial.\n" +
                 "Jovial: Alright then, kid, let's fight!\n");
    Entity jovial = Entity(1000, "Jovial Merryment", 100, 50);
    auto onWin = [=](Player player) -> UserInterface *
    {
        return new JovialAftermath(player, "win");
    };
    auto onLose = [=](Player player) -> UserInterface *
    {
        return new JovialAftermath(player, "lose");
    };
    return new Battle(player, jovial, 0, onWin, onLose);
}
References colorizeText(), UIWithPlayer::player, printAnimate(), and YELLOW.
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp