FirstChoice Class Reference
The part after the player meets the mysterious stranger.
#include <ui.h>
Public Member Functions
FirstChoice (Player player)
UserInterface * render () override
Public Member Functions inherited from UIWithPlayer
UIWithPlayer ()
UIWithPlayer (Player player)
Public Member Functions inherited from UserInterface
virtual ~UserInterface ()
Public Attributes
list< string > stayResps
Public Attributes inherited from UIWithPlayer
Player player
Public Attributes inherited from UserInterface
bool quitGame = false
Detailed Description
The part after the player meets the mysterious stranger.
The player can stay for funny dialogue.
Definition at line 98 of file ui.h.
Constructor & Destructor Documentation
FirstChoice()
FirstChoice::FirstChoice (Player player)
Definition at line 311 of file ui.cpp.
: UIWithPlayer(player) {}
References UIWithPlayer::player, and UIWithPlayer::UIWithPlayer().
Member Function Documentation
render()
UserInterface * FirstChoice::render () [override], [virtual]
Implements UserInterface.
Definition at line 313 of file ui.cpp.
{
    cout << "[1] Stay" << endl
         << "[2] Leave" << endl;
    int userInput = inputNum();
    cout << endl;
    if (userInput == 1)
    {
        printAnimate(stayResps.front() + "\n");
        if (stayResps.size() > 1)
        {
            stayResps.pop_front();
        }
        return this;
    }
    else if (userInput == 2)
    {
        return new JovialCutscene(player);
    }
    else
    {
        cout << "That's not one of the options!" << endl;
        return this;
    }
}
References inputNum(), UIWithPlayer::player, printAnimate(), and stayResps.
Member Data Documentation
stayResps
list<string> FirstChoice::stayResps
Initial value:
= {
        "Hello? I said get out.",
        "Come on man. I have stuff to do. Please leave.",
        "I'm gonna run out of dialogue options here. The devs didn't give me that many lines.",
        "Alright, I'm giving you the silent treatment.",
        "..."}
Definition at line 101 of file ui.h.
                             {
        "Hello? I said get out.",
        "Come on man. I have stuff to do. Please leave.",
        "I'm gonna run out of dialogue options here. The devs didn't give me that many lines.",
        "Alright, I'm giving you the silent treatment.",
        "..."};
Referenced by render().
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp