StrengthPotion Class Reference
Increases player ATK.
#include <items.h>
Public Member Functions
StrengthPotion (int c)
bool use (Player &player) override
string getDesc () override
Public Member Functions inherited from IPotion
IPotion (string n, string d, int c, int strength)
int getStrength ()
Public Member Functions inherited from IPlayerItem
IPlayerItem (string n, string t, string d, int c)
Public Member Functions inherited from IItem
IItem (string n, string t, string d, int c)
virtual ~IItem ()
string getName ()
string getType ()
void increment (int amount)
void decrement (int amount)
int getCount ()
bool isInfinite ()
bool isDepleted ()
bool matches (IItem *item)
Additional Inherited Members
Public Attributes inherited from IPotion
int strength
Detailed Description
Increases player ATK.
Definition at line 66 of file items.h.
Constructor & Destructor Documentation
StrengthPotion()
StrengthPotion::StrengthPotion (int c)
Definition at line 75 of file items.cpp.
: IPotion("Strength Potion", "", c, 100) {}
References IPotion::IPotion().
Member Function Documentation
getDesc()
string StrengthPotion::getDesc () [override], [virtual]
Reimplemented from IItem.
Definition at line 76 of file items.cpp.
{
    return "Increases the user's ATK by " + to_string(strength) + "!";
}
References IPotion::strength.
use()
bool StrengthPotion::use (Player & player) [override], [virtual]
Implements IPlayerItem.
Definition at line 81 of file items.cpp.
{
    player.boostAtk(strength);
    cout << "Your ATK increased by " + to_string(strength) + "!" << endl;
    cout << "Your new ATK is " + to_string(player.getAtk()) + "!" << endl;
    return true;
}
References Entity::boostAtk(), Entity::getAtk(), and IPotion::strength.
The documentation for this class was generated from the following files:
src/items.h
src/items.cpp