ShopMenu Class Reference
The main menu after all the cutscenes and stuff.
#include <ui.h>
Public Member Functions
ShopMenu (Player player)
UserInterface * render () override
Public Member Functions inherited from UIWithPlayer
UIWithPlayer ()
UIWithPlayer (Player player)
Public Member Functions inherited from UserInterface
virtual ~UserInterface ()
Additional Inherited Members
Public Attributes inherited from UserInterface
bool quitGame = false
Protected Attributes inherited from UIWithPlayer
Player player
Detailed Description
The main menu after all the cutscenes and stuff.
Definition at line 50 of file ui.h.
Constructor & Destructor Documentation
ShopMenu()
ShopMenu::ShopMenu (Player player)
Definition at line 157 of file ui.cpp.
: UIWithPlayer(player) {}
References UIWithPlayer::player, and UIWithPlayer::UIWithPlayer().
Member Function Documentation
render()
UserInterface * ShopMenu::render () [override], [virtual]
Implements UserInterface.
Definition at line 159 of file ui.cpp.
{
    cout << "Welcome to the shop! What would you like to buy?" << endl;
    Shop shop;
    shop.addItem(new HealthPotion(1), 50);
    shop.addItem(new StrengthPotion(1), 70);
    shop.listItems(player);
    int userInput = inputNum();
    if (userInput == 0)
    {
        return new MainMenu(player);
    }
    else
    {
        shop.buyItem(player, userInput);
    }
    return this;
}
References Shop::addItem(), Shop::buyItem(), inputNum(), Shop::listItems(), and UIWithPlayer::player.
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp