IWeapon Class Reference
Weapons set the type to "Weapon" and implement the use function cuz all weapons attack lmao.
#include <items.h>
Public Member Functions
IWeapon (string name, string desc, int count, int dmg)
bool use (Player &player, Entity &enemy) override
Public Member Functions inherited from IEnemyItem
IEnemyItem (string n, string t, string d, int c)
Public Member Functions inherited from IItem
IItem (string n, string t, string d, int c)
virtual ~IItem ()
Public Attributes
int dmg
Public Attributes inherited from IItem
string name
string type
string desc
int count
Detailed Description
Weapons set the type to "Weapon" and implement the use function cuz all weapons attack lmao.
Derived classes only need to set the name, desc, and dmg in the constructor
Definition at line 54 of file items.h.
Constructor & Destructor Documentation
IWeapon()
IWeapon::IWeapon (string name, string desc, int count, int dmg)
Definition at line 29 of file items.cpp.
: IEnemyItem(name, "Weapon", desc, count), dmg(dmg) {}
References IItem::count, IItem::desc, dmg, IEnemyItem::IEnemyItem(), and IItem::name.
Referenced by CoolStick::CoolStick(), and Yamato::Yamato().
Member Function Documentation
use()
bool IWeapon::use (Player & player, Entity & enemy) [override], [virtual]
Implements IEnemyItem.
Definition at line 30 of file items.cpp.
{
    player.attack(enemy, dmg);
    return true;
}
References Entity::attack(), and dmg.
Member Data Documentation
dmg
int IWeapon::dmg
Definition at line 57 of file items.h.
Referenced by IWeapon(), and use().
The documentation for this class was generated from the following files:
src/items.h
src/items.cpp