IItem Class Reference
Base class for all items in the game.
#include <items.h>
Public Member Functions
IItem (string n, string t, string d, int c)
virtual ~IItem ()
virtual string getDesc ()
string getName ()
string getType ()
void increment (int amount)
void decrement (int amount)
int getCount ()
bool isInfinite ()
bool isDepleted ()
bool matches (IItem *item)
Private Attributes
string desc
string name
string type
int count
A count of -1 means the item can be used infinitely.
Detailed Description
Base class for all items in the game.
Definition at line 10 of file items.h.
Constructor & Destructor Documentation
IItem()
IItem::IItem (string n, string t, string d, int c)
Definition at line 8 of file items.cpp.
: name(n), type(t), desc(d), count(c) {}
References count, desc, name, and type.
Referenced by IEnemyItem::IEnemyItem(), IPlayerItem::IPlayerItem(), matches(), and ~IItem().
~IItem()
IItem::~IItem () [virtual], [default]
References IItem().
Member Function Documentation
decrement()
void IItem::decrement (int amount)
Definition at line 27 of file items.cpp.
                                {
    count -= amount;
}
References count.
Referenced by Inventory::useItem().
getCount()
int IItem::getCount ()
Definition at line 31 of file items.cpp.
                    {
    return count;
}
References count.
Referenced by Inventory::addItem().
getDesc()
string IItem::getDesc () [virtual]
Reimplemented in CoolStick, HealthPotion, StrengthPotion, and Yamato.
Definition at line 11 of file items.cpp.
                      {
    return desc;
}
References desc.
getName()
string IItem::getName ()
Definition at line 15 of file items.cpp.
                      {
    return name;
}
References name.
Referenced by Inventory::addItem(), and Shop::buyItem().
getType()
string IItem::getType ()
Definition at line 19 of file items.cpp.
                      {
    return type;
}
References type.
increment()
void IItem::increment (int amount)
Definition at line 23 of file items.cpp.
                                {
    count += amount;
}
References count.
isDepleted()
bool IItem::isDepleted ()
Definition at line 39 of file items.cpp.
                       {
    return count == 0;
}
References count.
Referenced by Inventory::useItem().
isInfinite()
bool IItem::isInfinite ()
Definition at line 35 of file items.cpp.
                       {
    return count == -1;
}
References count.
Referenced by Inventory::useItem().
matches()
bool IItem::matches (IItem * item)
Definition at line 43 of file items.cpp.
                               {
    return name == item->name; // Kinda bad implementation but it works for now
}
References IItem(), and name.
Member Data Documentation
count
int IItem::count [private]
A count of -1 means the item can be used infinitely.
Definition at line 16 of file items.h.
Referenced by decrement(), getCount(), IItem(), increment(), isDepleted(), isInfinite(), and Weapon::Weapon().
desc
string IItem::desc [private]
Definition at line 13 of file items.h.
Referenced by getDesc(), IItem(), and Weapon::Weapon().
name
string IItem::name [private]
Definition at line 14 of file items.h.
Referenced by getName(), IItem(), matches(), and Weapon::Weapon().
type
string IItem::type [private]
Definition at line 15 of file items.h.
Referenced by getType(), and IItem().
The documentation for this class was generated from the following files:
src/items.h
src/items.cpp