src/extras.h File Reference
#include <chrono>
#include <thread>
#include <iostream>
Enumerations
enum Color {
RED = 31
, GREEN = 32
, YELLOW = 33
, BLUE = 34
,
MAGENTA = 35
, CYAN = 36
, WHITE = 37
 }
ANSI color codes for colored text (ANSI)
Functions
string padTo (string str, const size_t num, const char paddingChar=' ')
Centers text in a given num of characters.
void sleepMS (int ms)
string colorizeText (string msg, Color color)
Colors text.
int inputNum ()
Gets an integer from the user. Loops until a valid integer is entered.
void printAnimate (string msg, int delay=10, bool animate=true)
Outputs a text character by character with a given delay.
Enumeration Type Documentation
Color
enum Color
ANSI color codes for colored text (ANSI)
Enumerator
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
Definition at line 15 of file extras.h.
{
    RED = 31,
    GREEN = 32,
    YELLOW = 33,
    BLUE = 34,
    MAGENTA = 35,
    CYAN = 36,
    WHITE = 37
};
Function Documentation
colorizeText()
string colorizeText (string msg, Color color)
Colors text.
Usually used like this: \033[31m Your Text Here \033[0m, where 31 is the color code for red.
Definition at line 22 of file extras.cpp.
{
    return string("\033[") + to_string(color) + "m" + msg + "\033[0m";
}
Referenced by Player::addMoney(), Shop::buyItem(), Shop::listItems(), GambleMenu::render(), JovialAftermath::render(), and JovialCutscene::render().
inputNum()
int inputNum ()
Gets an integer from the user. Loops until a valid integer is entered.
Definition at line 27 of file extras.cpp.
{
    int result;
    while (!(cin >> result))
    {
        cin.clear();
        cin.ignore(numeric_limits<streamsize>::max(), '\n');
        cout << "That's not a number!" << std::endl;
    }
    return result;
}
Referenced by Battle::render(), FirstChoice::render(), MainMenu::render(), ShopMenu::render(), and StartMenu::render().
padTo()
string padTo (string str, const size_t num, const char paddingChar = ' ')
Centers text in a given num of characters.
Definition at line 4 of file extras.cpp.
{
    if (num > str.size())
    {
        div_t divided = div(num - str.size(), 2);
        size_t leftSpace = divided.quot;
        size_t rightSpace = divided.quot + divided.rem;
        str.insert(str.begin(), leftSpace, paddingChar);
        str.insert(str.end(), rightSpace, paddingChar);
    }
    return str;
}
Referenced by Inventory::listItems().
printAnimate()
void printAnimate (string msg, int delay = 10, bool animate = true)
Outputs a text character by character with a given delay.
Definition at line 42 of file extras.cpp.
{
    // if (!animate)
    if (true)
    {
        cout << msg;
        return;
    }
    for (auto &ch : msg)
    {
        cout << ch;
        sleepMS(delay);
    }
}
References sleepMS().
Referenced by Inventory::addItem(), Entity::fullyHeal(), FirstChoice::render(), GameOver::render(), IntroDialogue::render(), JovialAftermath::render(), JovialCutscene::render(), and MainMenu::render().
sleepMS()
void sleepMS (int ms)
Definition at line 17 of file extras.cpp.
{
    this_thread::sleep_for(chrono::milliseconds(ms));
}
Referenced by printAnimate().